# test against both regular Ruby and RubyMotion
language: ruby
cache:
  - bundler

# latest stable/supported versions
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - (ruby --version)

gemfile:
  - Gemfile

script:
  - bundle exec rake spec

jobs:
  include:
    - stage: rubymotion
      os: osx
      osx_image: xcode10.2
      language: objective-c
      cache:
        bundler: false
      script:
        - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
        - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
        - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
        - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
        - sudo mkdir -p ~/Library/RubyMotion/build
        - sudo chown -R travis ~/Library/RubyMotion
        - eval "sudo motion activate $RUBYMOTION_LICENSE"
        - sudo motion update && motion repo
        - cd rubymotion
        - bundle install --gemfile=./Gemfile --jobs=3 --retry=3
        - bundle exec rake spec
